### ISSUE TITLE
Update instruction on README

### ISSUE THREAD

**Issue by nekowinston** [caarlos0/dotfiles#1]
Hey,
Feels pretty weird to open an issue on someone's dotfiles 😅 

https://github.com/caarlos0/dotfiles.nix/blob/5bae58fc9a32af185ff26e501599b80e6552c54f/README.md?plain=1#L59-L63

Since you're using a Flake, wouldn't the nixpkgs from `flake.nix` `inputs` take precedence?
https://github.com/caarlos0/dotfiles.nix/blob/5bae58fc9a32af185ff26e501599b80e6552c54f/flake.nix#L4-L5

`nix flake update` or `nix flake lock --update-input nixpkgs` (to only update the specified input) would probably be the correct command to run.

**Comment by caarlos0** [comment]
ah probably, I'm not 100% sure what I'm doing with nix yet :D 

thanks, fixed the readme 💚

**Comment by nekowinston** [comment]
It's a wild ride, hope you're enjoying it!
Also switched my dots to Nix at the start of January, loving it so far.
